import bodyParser from "body-parser";
import express from "express";
import fs from "fs";
import path from "path";
import swaggerUi from "swagger-ui-express";
import { RegisterRoutes } from "./routes";

const app = express();
app.use(bodyParser.json());

// Auto-generated by TSOA
RegisterRoutes(app);

// Swagger UI
app.use("/public", express.static("public"));
const openapiPath = path.join(__dirname, "..", "public", "openapi.json");
const openapi = JSON.parse(fs.readFileSync(openapiPath, "utf8"));
app.use("/docs", swaggerUi.serve, swaggerUi.setup(openapi));

//  check
app.get("/", (_, res) => {
  res.send("TSOA Todo API");
});

const port = 3000;
app.listen(port, () =>
  console.log(`Server running at http://localhost:${port}`)
);
